[package]
name = "backendsouls-json-hal"
version = "0.1.0"
edition = "2021"

[dependencies]
getset = "0.1.2"
derive_builder = "0.12.0"

serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
serde_with = "3.4.0"
